spring:
  application:
    name: pruebacapitol
  datasource:
    url: jdbc:h2:mem:pruebacapitol
    driverClassName: org.h2.Driver
    username: developer
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration/ddl,classpath:db/migration/dml